/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_wtao_service_ScreenCoordsService_NativeEventParserDaemon */

#ifndef _Included_me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
#define _Included_me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
#ifdef __cplusplus
extern "C" {
#endif
#undef me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_MIN_PRIORITY
#define me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_MIN_PRIORITY 1L
#undef me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_NORM_PRIORITY
#define me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_NORM_PRIORITY 5L
#undef me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_MAX_PRIORITY
#define me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_MAX_PRIORITY 10L
#undef me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_TIME_OUT_MILLIS
#define me_wtao_service_ScreenCoordsService_NativeEventParserDaemon_TIME_OUT_MILLIS 10000LL
/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getDownTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getDownTime
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getEventTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getEventTime
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getAction
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getAction
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getPrecision
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getPrecision
  (JNIEnv *, jobject, jint);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getPointerCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getPointerCount
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getPointerIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getPointerIds
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    getPointerCoords
 * Signature: ()[Landroid/view/MotionEvent/PointerCoords;
 */
JNIEXPORT jobjectArray JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_getPointerCoords
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    recycle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_recycle
  (JNIEnv *, jobject);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    init
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_init
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     me_wtao_service_ScreenCoordsService_NativeEventParserDaemon
 * Method:    doInBackground
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_wtao_service_ScreenCoordsService_00024NativeEventParserDaemon_doInBackground
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
